### ISSUE TITLE
GH "Source" button doesn't render in Firefox

### ISSUE THREAD

**Issue by weddleben** [VictoriqueMoe/WaifuVault#18]
The GitHub source button doesn't show up in Firefox:

<img width="1321" alt="1" src="https://github.com/VictoriqueMoe/WaifuVault/assets/107364642/8572378a-d79b-4ef0-93d6-0060388db505">

I tested on a Windows machine and a Mac and get the same result. It's oddly rendering it as an iFrame for some reason?
<img width="627" alt="3" src="https://github.com/VictoriqueMoe/WaifuVault/assets/107364642/7a5923a1-8587-44b7-ae15-4b8cf18a7f96">

When I open up the network tab I see this:
<img width="1440" alt="4" src="https://github.com/VictoriqueMoe/WaifuVault/assets/107364642/ca8482b4-dfed-4f89-b828-baa2b7206e34">

It's behaving a bit strange in Chrome on my Mac as well. Anyways, just thought I'd mention...

**Comment by VictoriqueMoe** [comment]
That's strange considering that u use Firefox, and it's fine. It looks to me like a adblock issue? The code itself was generated from https://buttons.github.io/

**Comment by weddleben** [comment]
Jesus, it's my Dashlane extension! Sorry, I didn't realize Dashlane behaved like that...it's just for passwords...weird.

**Comment by VictoriqueMoe** [comment]
> Jesus, it's my Dashlane extension! Sorry, I didn't realize Dashlane behaved like that...it's just for passwords...weird.

valid issue. if dashlane thinks this is an input. i have changed it

**Comment by weddleben** [comment]
thanks for making me feel slightly less stupid :) it's possible that some other types of common extensions could behave similarly, so your change makes sense. plus is now matches the other bootstrap buttons
